### ISSUE TITLE
Terminal text displaying chopped

### ISSUE THREAD

**Issue by ltwalt** [gitatomic/atomic_public#2]
All text in the terminal window appears chopped. I have adjusted everything in the terminal options and have also tried reverting back to version 1.0.3. This only happens on my laptop. My desktop computer is running fine. My laptop was doing fine until I updated to version 1.0.6.

![image](https://user-images.githubusercontent.com/8409071/50376591-dff79700-05dc-11e9-942c-e56d65e3bd35.png)

**Comment by gitatomic** [comment]
Hi Walt,
That happens when you have a small font size set in the terminal page and the zoom on the actual terminal window is larger than the font size set. Try the following two steps:
a) In the Terminal settings page, set the font size to let's say 20
b) On the actual terminal window, using the mouse wheel, zoom out so the font size is in correct zoom and nothing is chopped.
Let me know if this works for you.
Best regards
Artur

**Comment by ltwalt** [comment]
Artur,

That worked. I didn't have a mouse connected to my laptop so didn't have
the wheel to adjust the zoom.

Thanks,
Best,
Walt

**Comment by gitatomic** [comment]
Hi Walt, 
So happy that I was able to help ;)
Best regards and have a Happy Christmas!

Artur
